# [作業目標-Part1]
在一個陣列中放入多屬性陣列，進一步對陣列做運算
作業重點
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:
```
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]
```
將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
呈上題，將array中體重(weight)數據集取出算出全部平均體重
呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [ ]:
import numpy as np 

In [ ]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [ ]:

#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重

#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重

#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重

# [作業目標-Part2]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
# 載入 NumPy 套件
import numpy as np

#呼叫 zeros(),建立元素全為 0的陣列
print(np.zeros((2, 3)))

#使用 empty() 函式則是不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定。
print(np.empty((2, 3)))


[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

#### Source01: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html
#### Source02: https://numpy.org/doc/stable/reference/random/generator.html


In [11]:
from numpy.random import default_rng
rng = default_rng()

a = rng.random((3,2))

# turn into interger
a_int = a.astype(int)

print(a)
print(a_int)

[[0.56488372 0.34200194]
 [0.91755701 0.37219595]
 [0.07019017 0.26149762]]
[[0 0]
 [0 0]
 [0 0]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [17]:
m = 20
n = 40
a_rangemton = a(m, n, size=(3,2))
print(a_rangemton)

TypeError: random() got multiple values for keyword argument 'size'